# Generated by Django 5.1.2 on 2025-01-06 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_stock_qty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='stock_qty',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
