# Generated by Django 5.1.4 on 2025-01-12 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_available_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='available_stock',
        ),
        migrations.RemoveField(
            model_name='product',
            name='stock_qty',
        ),
    ]
